-- ████╗   ██╗   ██████╗   ██████╗  ██████╗ ██╗  ██╗ ██████╗ ██╗     █████╗  ██████╗  ██████╗ ██████╗    ██╗ --
-- ██╔██╗  ██║ ██╔═════╝   ██╔══██╗ ██╔═══╝ ██║  ██║ ██╔═══╝ ██║    ██╔══██╗ ██╔══██╗ ██╔═══╝ ██╔══██╗   ██║ --
-- ██║╚██╗ ██║ ██║         ██║  ██║ █████╗  ██║  ██║ █████╗  ██║    ██║  ██║ ██████╔╝ █████╗  ██████╔╝   ██║ --
-- ██║ ╚██╗██║ ██║         ██║  ██║ ██╔══╝  ╚██╗██╔╝ ██╔══╝  ██║    ██║  ██║ ██╔═══╝  ██╔══╝  ██╔══██╗   ╚═╝ --
-- ██║  ╚████║ ╚═██████╗   ██████╔╝ ██████╗  ╚███╔╝  ██████╗ ██████╗╚█████╔╝ ██║      ██████╗ ██║  ██║   ██╗ --
-- ╚═╝   ╚═══╝   ╚═════╝   ╚═════╝  ╚═════╝   ╚══╝   ╚═════╝ ╚═════╝ ╚════╝  ╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝ --

-- ตั้งค่ากลับไป Filter ตั้งต้นเสมอเมื่อปิดกระเป๋า
Config.SetDefaultFilterOnCloseInventory = true

-- สามารถหา Icon ได้ที่	
-- หากต้องการให้ Filter ไหนเป็นค่าเริ่มต้นให้ใส่ default = true
Config.FilterIndicators = {
	{
		default = true,
		name = 'all',
                label = 'ทั้งหมด',
		icon = 'flowbite:grid-solid'
	},
	{
		name = 'account',
                label = 'การเงิน',
		icon = 'solar:wallet-bold'
	},
	{
		name = 'key',
                label = 'กุญแจ',
		icon = 'solar:key-bold'
	},
	{
		name = 'accessory',
                label = 'เครื่องแต่งกาย',
		icon = 'famicons:shirt'
	},
	{
		name = 'food',
                label = 'อาหาร',
		icon = 'ion:fast-food'
	},
	{
		name = 'fashion',
                label = 'แฟชั่น',
		icon = 'mynaui:star-solid'
	},
	-- {
	-- 	name = 'illegal',
	-- 	label = 'ผิดกฎหมาย',
	-- 	icon = 'ion:ban'
	-- },
	{
		name = 'weapon',
		label = 'อาวุธ',
		icon = 'mdi:sword-cross'
	}
}

-- ใส่ค่า Filter ให้ตรงตามโหมดด้านบน โดนโหมดที่ไม่จำเป็นต้องใส่ Items ได้แก่ all, cloth
Config.FilterItems = {
	['key'] = {
		'vehicle_key',
		'house_key'
	},
	['food'] = {
		'bread',
		'water',
		'hamburger',
		'ecola',
		'sprunk',
	},
	['fashion'] = {
		'sm_baby_duck_chibi',
		'sm_cute_penguin_duck',
		'sm_duck_backpack',
		'sm_duck_dumpling',
		'sm_duck_floaty',
		'sm_duck_hoodie',
		'sm_duck_slipper',
		'happyxmasbag',
		'happyxmasbear',
		'happyxmaskanom',
		'happyxmasmail',
		'happyxmasstop',
		'xmastree',
		'xmastreeglasses',
		'xmastreehead',
		'xmastreelight',
		'meow_krathong3_fish',
		'meow_krathong3_otter01',
		'meow_krathong3_otter02',
		'meow_krathong3_firefly',
		'meow_krathong3_fish2',
		'zindear_moodeng_l',
		'zindear_moodeng_r',
		'zindear_moodeng_top',
		'zindear_moodeng_arm',
		'zindear_moodeng',
		'zindear_moodeng_head',
		'zindear_moodeng_bag',
		"ots_bag_cat_1",
		"ots_bag_cat_2",
		"ots_bag_cat_3",
		"ots_bag_cat_4",
		"zindearcat_arm_black",
		"zindearcat_arm_brown	",
		"zindearcat_arm_gray",
		"zindearcat_cloud_black",
		"zindearcat_cloud_brown",
		"zindearcat_cloud_gray",
		"zindearcat_head_black",
		"zindearcat_head_brown",
		"zindearcat_head_gray",
		"zindearcat_mou_black",
		"zindearcat_mou_brown",
		"zindearcat_mou_gray",
		"zindearcat_run_black",
		"zindearcat_run_brown",
		"zindearcat_run_gray",
		"zindearcat_sho_l_black",
		"zindearcat_sho_l_brown",
		"zindearcat_sho_l_gray",
		"zindearcat_sho_r_black",
		"zindearcat_sho_r_brown",
		"zindearcat_sho_r_gray",
		"zindearcat_wing_black",
		"zindearcat_wing_brown",
		'jarp_krahang',
		'jarp_krasue',
		'jarp_kuman',
		'jarp_nangrum',
		'jarp_pob',
		'yokaionibackdds',
		'yokaionimaskdds',
		'yokaionipoodds',
		'aidenta_sakurabodywing_fashion',
		'aidenta_sakuralion_fashion',
		'aidenta_sakurastar_fashion',
		'aidenta_sakurawing_fashion',
		'bag',
		'blueitim',
		'blueunicorn',
		'hatunicorn',
		'pinkitim',
		'pinkunicorn',
		'purpleunicorn',
		'rainbowitim',
		'whiteunicorn',
		'pikaboo_pigaboo_chinese_vampire',
		'pikaboo_pigaboo_angel',
		'pikaboo_pigaboo_frankenstein',
		'pikaboo_pigaboo_ghost',
		'pikaboo_pigaboo_pumpkin',
		'pikaboo_pigaboo_witch',
		'pikaboo_azukicat_hero',
		'pikaboo_azukicat_leg_left',
		'pikaboo_azukicat_leg_right',
		'pikaboo_azukicat_shoe_left',
		'pikaboo_azukicat_shoe_right',
		'pikaboo_azukicat_devil',
		'pikaboo_azukicat_cheerleader',
		'pikaboo_azukicat_car',
		'pikaboo_azukicat_bag',
		'pikaboo_azukicat_arm_right',
		'pikaboo_azukicat_arm_left',
		'pikaboo_azukicat_angel',
		'bbg_corgi1',
		'bbg_corgi2',
		'bbg_corgi3',
		'bbg_corgi4',
		'bbg_corgi5',
		'kirby_bag',
		'kirby_flying',
		'kirby_hug',
		'kirby_sleeping',
		'kirby_star',
		'pigcute',
		'upsetduck_ballet',
		'bbg_baby3_1',
		'bbg_baby3_2',
		'bbg_baby3_3',
		'bbg_baby3_4',
		'bbg_baby3_5',
		'bbg_baby3_6',
		'bbg_baby3_7',
		'bbg_baby3_8',
		'upsetduck_egg',
		'upsetduck_flower',
		'upsetduck_froggo',
		'upsetduck_missyou',
		'upsetduck_swimmer',
		'babyshop_fashion_lunalapin',
		'babyshop_fashion_umbraears',
		'babyshop_fashion_miniaturechic',
		'babyshop_fashion_finnysplash',
		'babyshop_fashion_shibe',
		'aidenta_mashmallow_bag',
		'aidenta_mashmallow_bag',
		'aidenta_marshmallow_head',
		'aidenta_mashmallow_arm',
		'aidenta_marshmallow_candy',
		'aidenta_marshmallow_effect',
		'aidenta_marshmallow_shoes_l',
		'aidenta_marshmallow_shoes_r',
		'drgon_fashion',
		'shinchan_dancing',
		'shinchan_hug',
		'shinchan_shiro',
		'meow_capibara_back',
		'meow_capybara_bag',
		'meow_capybara_hat',
		'meow_capybara_leg',
		'zincryblue',
		'zincrygreen',
		'zincrypink',
		'ppuffgirl',
		'gpuffgirl',
		'bpuffgirl',
		'butterbear_bag',
		'butterbear_cupid',
		'butterbear_dance',
		'butterbear_heart',
		'bagbunny',
		'bunny',
		'moonstar',
		'plantbunny',
		'ribbonbunny',
		'strawberrybunny',
		'ha',
		'hb',
		'hc',
		'hd',
		'he',
		'hf',
		'hg',
		'bbg_christ9',
		'bbg_christ10',
		'bbg_christ11',
		'bbg_christ1',
		'bbg_christ2',
		'bbg_christ3',    
		'bbg_christ6',
		'bbg_christ7',
		'bbg_christ8',   
		'zintoothless_whi_1',
		'zintoothless_whi_2',
		'zintoothless_whi_3',
		'reawx_christmas_evebear',
		'reawx_christmas_hat',
		'reawx_christmas_mary',
		'reawx_christmas_santacutie',
		'reawx_christmas_scarf',
		'reawx_christmas_snowman',
		'reawx_christmas_tress',
		'katana_japan_1',
		'katana_japan_2',
		'katana_japan_3',
		'ots_bag_cat_1',
		'ots_bag_cat_2',
		'ots_bag_cat_3',
		'kitsune_mask_1',
		'kitsune_mask_2',
		'meow_ots_1',
		'meow_ots_2',
		'meow_ots_3',
		'meow_ots_4',
		'ninja_neko_1',
		'ninja_neko_2',
		'ots_oni_mask_1',
		'ots_oni_mask_2',
		'ots_oni_mask_3',
		'ots_oni_mask_4',
		'ots_oni_mask_5',
		'scroll_ninja_1',
		'scroll_ninja_2',
		'tengu_mask',
		'coo_katana_1',
		'coo_katana_3',
		'wagasa_umbella_1',
		'wagasa_umbella_2',
		'aidenta_rabbit_ears',
		'aidenta_rabbit_bag',
		'aidenta_rabbit_pet',
		'aidenta_rabbit_carrot',
		'aidenta_rabbit_tails',
		'aidenta_rabbit_shoulder',
		'aidenta_rabbit_shoe_right',
		'aidenta_rabbit_shoe_left',
	},
	['illegal'] = {
		'wire',
		'cement',
	}
}

-- ซ่อนสิ่งของต่างๆจากการแสดงทั้งหมด (ตามหมวดหมู่สิ่งของ)
Config.HideItemsFromAllItemListByCategory = {
	['account'] = false,
	['item'] = false,
	['weapon'] = false,
	['key'] = false,
	['accessory'] = false,
	['fashion'] = true,
	-- Category หลักจะมีแค่นี้!
	-- *ค่าที่อยู่ใน Config.FilterItems จะเป็นแค่ Filter เท่านั้น ไม่ใช่ Category

	-- สำหรับ Custom ให้ใส่ชนิดของ Custom Item นั้นๆ
	['personal'] = false,
}

-- ซ่อนสิ่งของต่างๆจากการแสดงทั้งหมด (ตามชื่อของสิ่งของ)
Config.HideItemsFromAllItemListByName = {
    ['not_item'] = true,
    ['sakura-wisdom-gold-ss5-tw'] = true,
    ['sakura-wisdom-silver-ss5-tw'] = true,
    ['twitter_btp_ss2'] = true,
    ['twitter_btp_ss3'] = true,
    ['twitter_btp_ss4'] = true,
    ['twitter_btp_ss5'] = true,
    ['twitter_btp_ss6'] = true,
    ['twitter_btp_ss7'] = true,
    ['twitter_btp_ss8'] = true,
    ['twitter_daruma'] = true,
    ['twitter_fuji'] = true,
    ['twitter_ninja'] = true,
    ['twitter_pig'] = true,
    ['twitter_sakura'] = true,
    ['twitter_samurai'] = true,
    ['twitter_valentine'] = true,
	['vip_card_1day_ss10'] = true,
    ['vip_card_7day_ss10'] = true,
    ['vip_card_15day_ss10'] = true,
    ['vip_card_30day_ss10'] = true,
    -- ['vip_card'] = true,
    ['vip_card_1day_ss11'] = true,
    ['vip_card_7day_ss11'] = true,
    ['vip_card_15day_ss11'] = true,
    ['vip_card_30day_ss11'] = true,
}
